'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WarrantViewUpdate

    '''<summary>
    '''lblSearchSceen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchSceen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUpdateSucess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUpdateSucess As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblErrorMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWarantNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWarantNum As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtWarrantNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWarrantNum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblApplDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApplDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtApplDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApplDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbdDefMiddName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbdDefMiddName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbdDefFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbdDefFirstName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDefLast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDefLast As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDefAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDefAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDeffAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDeffAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDefMiddle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDefMiddle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDefFirst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDefFirst As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbdDefLastName0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbdDefLastName0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPlaitMiddleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlaitMiddleName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlainLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlainLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPlaitFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlaitFirstName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPlaitLastName0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlaitLastName0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlainFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlainFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPlaintAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlaintAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPlainMiddleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlainMiddleName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtWarrantAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWarrantAmt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtWarrJudgeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWarrJudgeName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblWarrJudgeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWarrJudgeName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtWarrantDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWarrantDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblWarrLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWarrLocation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPlainAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlainAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWarrantAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWarrantAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtWarrantLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWarrantLocation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblApplJudgeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApplJudgeName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWarDisposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWarDisposition As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWarrantDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWarrantDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtWarrantPhone1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWarrantPhone1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtWarrDisposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWarrDisposition As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtWarrantCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWarrantCharge As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblWarrantPhone1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWarrantPhone1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWarrCharge0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWarrCharge0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOffCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOffCharge As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblApplAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApplAmt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDismDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDismDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDismAmt0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDismAmt0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtappJudgeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtappJudgeName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtApplAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApplAmt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDismisAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDismisAmt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDismisDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDismisDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDockDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDockDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOffenceCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOffenceCharge As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDockDate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDockDate1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDockDate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDockDate2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDockDate3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDockDate3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDocDescr3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDocDescr3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDockDate4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDockDate4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDocDescr2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDocDescr2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDockDate5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDockDate5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDocDescr5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDocDescr5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDockDesc0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDockDesc0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDocDescr1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDocDescr1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDocDescr4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDocDescr4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btSearchScreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSearchScreen As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdate As Global.System.Web.UI.WebControls.Button
End Class
